Homework with output is added
andrii-kovsh/dz-8 pull request #1
Opened 2023-07-18 04:50 UTC by andrii-kovsh

2023-07-18 19:53 UTC, yurii-voronenko commented on src/main/java/StudentsGroup.java
> +    }
groupLeader could be added in constructor instead of adding it later

2023-07-18 19:56 UTC, yurii-voronenko requested changes

2023-07-18 19:56 UTC, yurii-voronenko commented on src/main/java/StudentsGroup.java
> +        // Логіка позначення завдання як виконаного для зазначеного студента
Missed code here?

2023-07-18 19:56 UTC, yurii-voronenko commented on src/main/java/StudentsGroup.java
> +
You have list of students and list of tasks, so you have to add one more structure to mark that student finished task

2023-07-18 21:58 UTC, andrii-kovsh commented on src/main/java/StudentsGroup.java
> +    }
edited code as per comment

2023-07-18 21:58 UTC, andrii-kovsh commented on src/main/java/StudentsGroup.java
> +
added code as per comment

2023-07-18 22:00 UTC, andrii-kovsh commented on src/main/java/StudentsGroup.java
> +        // Логіка позначення завдання як виконаного для зазначеного студента
completely forgot about this implementation, please see new commit with logic of task completion and output

2023-08-01 21:21 UTC, yurii-voronenko requested changes

2023-08-01 21:21 UTC, yurii-voronenko commented on src/main/java/StudentsGroup.java
> +    private final Map<String, Student> completedTasks;
Currently you can mark only one task for one student but relation is multiple to multiple. Use structure `Map<String, List<Student>>`

2023-08-01 21:21 UTC, yurii-voronenko commented on src/main/java/StudentsGroup.java
> +        this.groupLeader = groupLeader;
Just add group leader to students list here

2023-08-01 21:21 UTC, yurii-voronenko commented on src/main/java/StudentsGroup.java
> +        if (newGroupLeader != null) {
Check if group leader already present in students list if not then add

2023-08-01 21:21 UTC, yurii-voronenko commented on src/main/java/StudentsGroup.java
> +        students.remove(student);
Check that you do not remove leader here

2023-08-14 21:45 UTC, yurii-voronenko commented on src/main/java/StudentsGroup.java
> +        if (newGroupLeader != null && !students.contains(newGroupLeader)) {
It's not what I was asking, cold should be like this:
```
if (newGroupLeader == null)
   throw new RuntimeException("Group leader can't be null");
this.groupLeader = newGroupLeader;
if (!students.contains(newGroupLeader))
   students.add(newGroupLeader);
```

2023-08-14 21:47 UTC, yurii-voronenko approved these changes
Done

2023-08-15 08:24 UTC, merged